import type { StoreShape } from './types'

// Deterministic dummy data so the admin control room looks alive on first run.
// Timestamps are fixed ISO strings (no runtime randomness in the seed itself).

export function SEED(): StoreShape {
  return {
    users: [
      {
        id: 'usr_admin',
        email: 'admin@newindiamanifesto.in',
        phone: '+91 82087 37624',
        fullName: 'Control Room',
        role: 'admin',
        district: 'solapur',
        status: 'active',
        createdAt: '2026-06-01T09:00:00.000Z',
      },
      {
        id: 'usr_f1',
        email: 'sanika@shivardairy.in',
        phone: '+91 90210 11223',
        fullName: 'Sanika Pawar',
        role: 'founder',
        district: 'solapur',
        status: 'active',
        createdAt: '2026-07-02T09:00:00.000Z',
      },
      {
        id: 'usr_f2',
        email: 'imran@khadivillage.in',
        phone: '+91 98330 55110',
        fullName: 'Imran Shaikh',
        role: 'founder',
        district: 'sangli',
        status: 'active',
        createdAt: '2026-07-05T09:00:00.000Z',
      },
    ],

    founderApplications: [
      {
        id: 'fa_1',
        userId: 'usr_f1',
        fullName: 'Sanika Pawar',
        email: 'sanika@shivardairy.in',
        phone: '+91 90210 11223',
        district: 'solapur',
        ventureName: 'Shivar Dairy',
        stage: 'early_revenue',
        sector: 'agritech',
        oneLiner: 'Collective cold-chain dairy for 40 smallholder farmers near Akkalkot.',
        problem:
          'Smallholder farmers lose 20-30% of milk value to middlemen and spoilage. There is no local chilling or fair-price collection point.',
        whatBuilt:
          'A village collection centre with a solar chiller, daily fair-price payouts over UPI, and packaged dairy sold in nearby towns.',
        teamSize: 4,
        lookingFor: ['mentorship', 'network', 'capital'],
        capitalContext:
          'Support would go toward a second chilling unit and working capital for daily farmer payouts.',
        links: 'shivardairy.in',
        videoUrl: null,
        videoDuration: null,
        consentShareWithMentors: true,
        consentDataProcessing: true,
        consentCampaignUpdates: true,
        internalStatus: 'under_review',
        createdAt: '2026-07-02T09:10:00.000Z',
      },
      {
        id: 'fa_2',
        userId: 'usr_f2',
        fullName: 'Imran Shaikh',
        email: 'imran@khadivillage.in',
        phone: '+91 98330 55110',
        district: 'sangli',
        ventureName: 'Khadi Village Co',
        stage: 'prototype',
        sector: 'consumer',
        oneLiner: 'Modern handloom khadi apparel made by weaver clusters in Sangli.',
        problem:
          'Traditional weavers earn very little and are losing the craft; there is no direct-to-consumer brand carrying their work to cities.',
        whatBuilt:
          'A small D2C brand with 12 weaver families, an online store, and two pop-up stalls at city exhibitions.',
        teamSize: 3,
        lookingFor: ['network', 'pilot_customers'],
        capitalContext:
          'Support would help onboard 20 more weaver families and set up a shared finishing unit.',
        links: 'instagram.com/khadivillage',
        videoUrl: null,
        videoDuration: null,
        consentShareWithMentors: true,
        consentDataProcessing: true,
        consentCampaignUpdates: false,
        internalStatus: 'shortlisted',
        createdAt: '2026-07-05T09:20:00.000Z',
      },
      {
        id: 'fa_3',
        userId: 'usr_f3',
        fullName: 'Vaishnavi Kale',
        email: 'vaishnavi@padhaipoint.in',
        phone: '+91 91560 43871',
        district: 'satara',
        ventureName: null,
        stage: 'idea',
        sector: 'edtech',
        oneLiner: 'After-school spoken-English and computer basics for rural students.',
        problem:
          'Students in taluka schools rarely get spoken-English or basic computer exposure, which blocks them from jobs and college.',
        whatBuilt:
          'Just an idea for now — a low-cost evening centre model with recorded lessons and a local facilitator.',
        teamSize: 1,
        lookingFor: ['mentorship', 'capital'],
        capitalContext:
          'Support would fund a pilot centre for one taluka and a facilitator stipend for six months.',
        links: '',
        videoUrl: null,
        videoDuration: null,
        consentShareWithMentors: false,
        consentDataProcessing: true,
        consentCampaignUpdates: true,
        internalStatus: 'received',
        createdAt: '2026-07-11T09:30:00.000Z',
      },
      {
        id: 'fa_4',
        userId: 'usr_f4',
        fullName: 'Ganesh More',
        email: 'ganesh@bhusolar.in',
        phone: '+91 99700 12048',
        district: 'kolhapur',
        ventureName: 'Bhu Solar',
        stage: 'growth',
        sector: 'deeptech',
        oneLiner: 'Affordable solar irrigation pumps on a pay-per-use model for farmers.',
        problem:
          'Diesel irrigation is expensive and unreliable; upfront solar cost is out of reach for most small farmers.',
        whatBuilt:
          '60 pumps deployed across three talukas on a pay-per-use subscription, with remote monitoring.',
        teamSize: 9,
        lookingFor: ['capital', 'network', 'pilot_customers'],
        capitalContext:
          'Support would extend the revolving asset pool so more farmers can join without upfront cost.',
        links: 'bhusolar.in',
        videoUrl: null,
        videoDuration: null,
        consentShareWithMentors: true,
        consentDataProcessing: true,
        consentCampaignUpdates: true,
        internalStatus: 'matched',
        createdAt: '2026-06-22T09:40:00.000Z',
      },
      {
        id: 'fa_5',
        userId: 'usr_f5',
        fullName: 'Prerna Jadhav',
        email: 'prerna@aarogyasakhi.in',
        phone: '+91 97640 88112',
        district: 'pune',
        ventureName: 'Aarogya Sakhi',
        stage: 'early_revenue',
        sector: 'healthtech',
        oneLiner: 'Trained women health workers running basic screening camps in villages.',
        problem:
          'Rural families skip preventive screening; the nearest diagnostics are hours away and intimidating.',
        whatBuilt:
          'A network of 18 trained "sakhis" running BP, sugar and haemoglobin camps, referring cases to partner clinics.',
        teamSize: 6,
        lookingFor: ['mentorship', 'network'],
        capitalContext:
          'Support would fund portable screening kits and training for 30 more health workers.',
        links: 'aarogyasakhi.in',
        videoUrl: null,
        videoDuration: null,
        consentShareWithMentors: true,
        consentDataProcessing: true,
        consentCampaignUpdates: true,
        internalStatus: 'under_review',
        createdAt: '2026-07-14T09:50:00.000Z',
      },
      {
        id: 'fa_6',
        userId: 'usr_f6',
        fullName: 'Akash Deshpande',
        email: 'akash@mandifair.in',
        phone: '+91 90040 77521',
        district: 'other',
        ventureName: 'MandiFair',
        stage: 'prototype',
        sector: 'fintech',
        oneLiner: 'Transparent digital khata and instant payments for mandi traders.',
        problem:
          'Farmers and small traders settle on paper khatas with delayed, opaque payments and disputes.',
        whatBuilt:
          'A simple app piloting with 2 mandis for digital weighing slips and same-day UPI settlement.',
        teamSize: 2,
        lookingFor: ['mentorship', 'capital', 'network'],
        capitalContext:
          'Support would fund the pilot rollout to five more mandis and compliance groundwork.',
        links: 'mandifair.in',
        videoUrl: null,
        videoDuration: null,
        consentShareWithMentors: false,
        consentDataProcessing: true,
        consentCampaignUpdates: false,
        internalStatus: 'rejected',
        createdAt: '2026-06-28T10:00:00.000Z',
      },
    ],

    mentorProfiles: [
      {
        id: 'mp_1',
        userId: 'usr_m1',
        fullName: 'Dr. Meera Kulkarni',
        email: 'meera@agritechlab.in',
        phone: '+91 98220 10101',
        expertiseAreas: ['Supply chain', 'Cold chain', 'FPOs'],
        sectors: ['agritech', 'consumer'],
        roleCompany: 'Founder, AgriTech Lab',
        yearsExperience: 18,
        capacity: 3,
        linkedin: 'linkedin.com/in/meerakulkarni',
        bio: 'Two decades building farmer-producer supply chains across western Maharashtra.',
        approvalStatus: 'approved',
        createdAt: '2026-06-15T09:00:00.000Z',
      },
      {
        id: 'mp_2',
        userId: 'usr_m2',
        fullName: 'Rahul Bhosale',
        email: 'rahul@scaleup.in',
        phone: '+91 99201 20202',
        expertiseAreas: ['Go-to-market', 'D2C', 'Branding'],
        sectors: ['consumer', 'edtech'],
        roleCompany: 'Growth Partner, ScaleUp',
        yearsExperience: 11,
        capacity: 5,
        linkedin: 'linkedin.com/in/rahulbhosale',
        bio: 'Helps early brands find their first 1,000 customers.',
        approvalStatus: 'approved',
        createdAt: '2026-06-18T09:00:00.000Z',
      },
      {
        id: 'mp_3',
        userId: 'usr_m3',
        fullName: 'Fatima Ansari',
        email: 'fatima@healthbridge.in',
        phone: '+91 98903 30303',
        expertiseAreas: ['Public health', 'Operations'],
        sectors: ['healthtech', 'social'],
        roleCompany: 'Program Director, HealthBridge',
        yearsExperience: 14,
        capacity: 2,
        linkedin: 'linkedin.com/in/fatimaansari',
        bio: 'Runs community health programmes across three states.',
        approvalStatus: 'pending',
        createdAt: '2026-07-10T09:00:00.000Z',
      },
      {
        id: 'mp_4',
        userId: 'usr_m4',
        fullName: 'Sandeep Rao',
        email: 'sandeep@fintechguild.in',
        phone: '+91 99404 40404',
        expertiseAreas: ['Payments', 'Compliance', 'Risk'],
        sectors: ['fintech'],
        roleCompany: 'Ex-VP, Payments Guild',
        yearsExperience: 16,
        capacity: 4,
        linkedin: 'linkedin.com/in/sandeeprao',
        bio: 'Built payments rails and navigated RBI compliance for two startups.',
        approvalStatus: 'pending',
        createdAt: '2026-07-16T09:00:00.000Z',
      },
    ],

    investorProfiles: [
      {
        id: 'ip_1',
        userId: 'usr_i1',
        fullName: 'Anjali Mehta',
        email: 'anjali@deccanangels.in',
        phone: '+91 98110 50505',
        investorType: 'angel',
        ticketMin: 200000,
        ticketMax: 2000000,
        sectors: ['agritech', 'consumer', 'social'],
        stageFocus: ['prototype', 'early_revenue'],
        firmName: 'Deccan Angels',
        linkedin: 'linkedin.com/in/anjalimehta',
        approvalStatus: 'approved',
        createdAt: '2026-06-20T09:00:00.000Z',
      },
      {
        id: 'ip_2',
        userId: 'usr_i2',
        fullName: 'Vikram Shetty',
        email: 'vikram@sahyadrivc.in',
        phone: '+91 99206 60606',
        investorType: 'vc',
        ticketMin: 2500000,
        ticketMax: 20000000,
        sectors: ['fintech', 'deeptech', 'healthtech'],
        stageFocus: ['early_revenue', 'growth'],
        firmName: 'Sahyadri Ventures',
        linkedin: 'linkedin.com/in/vikramshetty',
        approvalStatus: 'approved',
        createdAt: '2026-06-25T09:00:00.000Z',
      },
      {
        id: 'ip_3',
        userId: 'usr_i3',
        fullName: 'Nilesh Patil',
        email: 'nilesh@patilfamilyoffice.in',
        phone: '+91 98707 70707',
        investorType: 'family_office',
        ticketMin: 1000000,
        ticketMax: 10000000,
        sectors: ['agritech', 'social'],
        stageFocus: ['idea', 'prototype', 'early_revenue'],
        firmName: 'Patil Family Office',
        linkedin: 'linkedin.com/in/nileshpatil',
        approvalStatus: 'pending',
        createdAt: '2026-07-12T09:00:00.000Z',
      },
    ],

    expertProfiles: [
      {
        id: 'ep_1',
        userId: 'usr_e1',
        fullName: 'Prof. Sunita Deshmukh',
        email: 'sunita@agriuniv.in',
        phone: '+91 98220 80808',
        domain: 'Agricultural sciences',
        contribution: ['judge', 'curriculum'],
        bio: 'Professor of agri-sciences; designs applied curricula for rural entrepreneurs.',
        linkedin: 'linkedin.com/in/sunitadeshmukh',
        approvalStatus: 'approved',
        createdAt: '2026-06-19T09:00:00.000Z',
      },
      {
        id: 'ep_2',
        userId: 'usr_e2',
        fullName: 'Kabir Nair',
        email: 'kabir@policyforum.in',
        phone: '+91 99209 90909',
        domain: 'Public policy',
        contribution: ['policy', 'speak'],
        bio: 'Policy researcher focused on MSME and rural livelihoods.',
        linkedin: 'linkedin.com/in/kabirnair',
        approvalStatus: 'pending',
        createdAt: '2026-07-13T09:00:00.000Z',
      },
      {
        id: 'ep_3',
        userId: 'usr_e3',
        fullName: 'Ritu Agarwal',
        email: 'ritu@designcollective.in',
        phone: '+91 98101 11010',
        domain: 'Product design',
        contribution: ['judge', 'speak', 'curriculum'],
        bio: 'Design leader mentoring first-time founders on product and UX.',
        linkedin: 'linkedin.com/in/rituagarwal',
        approvalStatus: 'approved',
        createdAt: '2026-07-01T09:00:00.000Z',
      },
    ],

    bookOrders: [
      {
        id: 'bo_1',
        buyerName: 'Suresh Patil',
        buyerEmail: 'suresh.patil@example.in',
        buyerPhone: '+91 90000 11111',
        format: 'physical',
        quantity: 1,
        amount: 499,
        shippingAddress: 'Plot 12, Gandhi Nagar, Solapur, Maharashtra 413001',
        paymentGateway: 'razorpay',
        paymentId: 'pay_seed001',
        paymentStatus: 'paid',
        fulfillmentStatus: 'shipped',
        consentCampaignUpdates: true,
        createdAt: '2026-07-03T11:00:00.000Z',
      },
      {
        id: 'bo_2',
        buyerName: 'Meena Joshi',
        buyerEmail: 'meena.joshi@example.in',
        buyerPhone: '+91 90000 22222',
        format: 'ebook',
        quantity: 1,
        amount: 199,
        shippingAddress: null,
        paymentGateway: 'razorpay',
        paymentId: 'pay_seed002',
        paymentStatus: 'paid',
        fulfillmentStatus: 'delivered',
        consentCampaignUpdates: false,
        createdAt: '2026-07-06T11:00:00.000Z',
      },
      {
        id: 'bo_3',
        buyerName: 'Ajay Kulkarni',
        buyerEmail: 'ajay.k@example.in',
        buyerPhone: '+91 90000 33333',
        format: 'physical',
        quantity: 3,
        amount: 1497,
        shippingAddress: 'Flat 4B, Kothrud, Pune, Maharashtra 411038',
        paymentGateway: 'razorpay',
        paymentId: 'pay_seed003',
        paymentStatus: 'paid',
        fulfillmentStatus: 'pending',
        consentCampaignUpdates: true,
        createdAt: '2026-07-09T11:00:00.000Z',
      },
      {
        id: 'bo_4',
        buyerName: 'Farah Khan',
        buyerEmail: 'farah.khan@example.in',
        buyerPhone: '+91 90000 44444',
        format: 'ebook',
        quantity: 1,
        amount: 199,
        shippingAddress: null,
        paymentGateway: 'razorpay',
        paymentId: 'pay_seed004',
        paymentStatus: 'paid',
        fulfillmentStatus: 'delivered',
        consentCampaignUpdates: true,
        createdAt: '2026-07-15T11:00:00.000Z',
      },
      {
        id: 'bo_5',
        buyerName: 'Ramesh Yadav',
        buyerEmail: 'ramesh.y@example.in',
        buyerPhone: '+91 90000 55555',
        format: 'physical',
        quantity: 1,
        amount: 499,
        shippingAddress: 'Near Bus Stand, Karad, Satara, Maharashtra 415110',
        paymentGateway: 'razorpay',
        paymentId: 'pay_seed005',
        paymentStatus: 'created',
        fulfillmentStatus: 'pending',
        consentCampaignUpdates: false,
        createdAt: '2026-07-18T11:00:00.000Z',
      },
    ],

    pledges: [
      { id: 'pl_1', name: 'Kiran Salunkhe', email: 'kiran.s@example.in', phone: '+91 91000 10001', district: 'solapur', commitment: ['incubate', 'spread'], consentCampaignUpdates: true, createdAt: '2026-07-01T12:00:00.000Z' },
      { id: 'pl_2', name: 'Deepa Nair', email: 'deepa.n@example.in', phone: '+91 91000 10002', district: 'pune', commitment: ['mentor'], consentCampaignUpdates: true, createdAt: '2026-07-02T12:00:00.000Z' },
      { id: 'pl_3', name: 'Arjun Rane', email: 'arjun.r@example.in', phone: '+91 91000 10003', district: 'kolhapur', commitment: ['support', 'spread'], consentCampaignUpdates: true, createdAt: '2026-07-04T12:00:00.000Z' },
      { id: 'pl_4', name: 'Snehal More', email: 'snehal.m@example.in', phone: '+91 91000 10004', district: 'sangli', commitment: ['mentor', 'spread'], consentCampaignUpdates: true, createdAt: '2026-07-06T12:00:00.000Z' },
      { id: 'pl_5', name: 'Yusuf Shaikh', email: 'yusuf.s@example.in', phone: '+91 91000 10005', district: 'satara', commitment: ['incubate'], consentCampaignUpdates: true, createdAt: '2026-07-08T12:00:00.000Z' },
      { id: 'pl_6', name: 'Pooja Gaikwad', email: 'pooja.g@example.in', phone: '+91 91000 10006', district: 'pune', commitment: ['support'], consentCampaignUpdates: true, createdAt: '2026-07-10T12:00:00.000Z' },
      { id: 'pl_7', name: 'Mahesh Patil', email: 'mahesh.p@example.in', phone: '+91 91000 10007', district: 'solapur', commitment: ['mentor', 'support', 'spread'], consentCampaignUpdates: true, createdAt: '2026-07-12T12:00:00.000Z' },
      { id: 'pl_8', name: 'Aisha Sayyed', email: 'aisha.s@example.in', phone: '+91 91000 10008', district: 'other', commitment: ['spread'], consentCampaignUpdates: true, createdAt: '2026-07-14T12:00:00.000Z' },
    ],

    matches: [],
  }
}
